name: 中青看点
on:
  #workflow_dispatch:
  schedule:
    - cron: '10,20 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        User: ${{ github.event.repository.owner.id }}
    steps:

      - name: Checkout
        run: |
          git clone https://github.com/guakeliao/garbageCollection.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【中青看点】'
        run: |
          cd ~/js   
          node js/youth/youth.js
